<?php
namespace App\Supports;
class Constants {
    const STATUS_OPEN = "STATUS_OPEN";
    const STATUS_SUBMIT_BY_PETUGAS = "STATUS_SUBMIT_BY_PETUGAS";
    const STATUS_REJECTED_BY_PETUGAS = "STATUS_REJECTED_BY_PETUGAS";
    const STATUS_APPROVED_BY_PENGAWAS = "STATUS_APPROVED_BY_PENGAWAS";
    const STATUS_REJECTED_BY_ADMIN = "STATUS_REJECTED_BY_ADMIN";
    const STATUS_APPROVED_BY_ADMIN = "STATUS_APPROVED_BY_ADMIN";

    const LEVEL_REKAP_SLS = "LEVEL_REKAP_SLS";
    const LEVEL_REKAP_BS= "LEVEL_REKAP_BS";
    const LEVEL_REKAP_DESA = "LEVEL_REKAP_DESA";
    const LEVEL_REKAP_KECAMATAN = "LEVEL_REKAP_KECAMATAN";
    const LEVEL_REKAP_KABUPATEN = "LEVEL_REKAP_KABUPATEN";
    const LEVEL_REKAP_PROVINSI = "LEVEL_REKAP_PROVINSI";

    const JENIS_TEST_VALID_IF = "JENIS_TEST_VALID_IF";
    const JENIS_TEST_SHOW_IF = "JENIS_TEST_SHOW_IF";
    const JENIS_TEST_REQUIRED_IF = "JENIS_TEST_REQUIRED_IF";
    const JENIS_TEST_TOGGLER = "JENIS_TEST_TOGGLER";

    const JENIS_USER_ORGANIK = "JENIS_USER_ORGANIK";
    const JENIS_USER_NON_ORGANIK = "JENIS_USER_NON_ORGANIK";

}
